### PR TITLE
Feature/rr-26-refactoring

### PR DESCRIPTION
**Pull request by MateuszBednarczyk**
## Description

converting app logic into service layer, cleanup of the storage layer

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🇺🇸 Translation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by wzslr321 — COMMENTED** [review]
Overall looks really good, though I am not sure about logging_service placement. Should it really be in `logic` package? And since it forwards the call and returns ServiceResponse, the naming with `Log` prefix seems to be a little misleading, like it only logs and doesn't return anything. Your commits also showed that there will be needed some changes with a protobuf file, which is great - we will definitely have to modify .proto and make use of enums. 

Everything else LGTM, but I'd like to hear your opinion on aforementioned logging, before merging the PR.

**Comment by MateuszBednarczyk** [comment]
@wzslr321 you're right. Log prefix is completely misleading. Should we call it LogAndExecute+function name? Something like LogAndExecuteCreateUser. Also, don't merge it yet. I think that I shoud also change naming of some functions. For example storage function from create to save, service function from handle to just CreateUser, cuz i think that the handler is handling. I Hope you understand. Also as u mentioned, I'm not sure if logic package is best place for logging stuff, but I'll figure it out

**Comment by wzslr321** [comment]
@MateuszBednarczyk `LogAndExecute` seems to be reasonable. Save instead Create in storage function definitely fits better too. I personally would leave `handle` since it is a common practice in Golang,  also `CreateUser` may be confusing, because it is the exact name of gRPC functions in `api.go` and there is no clear separation without the prefix. In my opinion, a perfect middle-ground would be to leave handler prefix in UsersService, and change logging functions prefix to `LogAndHandle`. It would be perfectly clear what does what.

**Comment by MateuszBednarczyk** [comment]
@wzslr321 what do you think about adding `handle` prefix in `api.go` and deleting this prefix in the service layer?

**Comment by MateuszBednarczyk** [comment]
@wzslr321 I made up those changes I mentioned. Let me know what do you think.

**Review by wzslr321 — COMMENTED** [review]
The idea is really good, but unfortunately gRPC forces the Server to implement names matching those in protobuf definitions, so calls don't recognize current ones and return error 'NOT IMPLEMENTED'

**Review by wzslr321 — APPROVED** [review]
LGTM

**Pull request merged**
